apify/proxy-chain

- src/handler_forward.js
Requests sent through proxy chain with invalid headers caused the proxy chain to throw error and close connection. This skips the header instead.
> Fixed issue where invalid headers in request broke connection

- src/handler_tunnel_chain.js
- test/anonymize_proxy.js
The handler_tunnel_chain.js file creates a CONNECT request to the real proxy and sets the desired target in the path parmater of the request options.
As far as I know the standard it to set it in the 'host' header...
> Fix #32 - tunnel chain should set the target host in the 'host' heaer and not in the path parameter

- src/tcp_tunnel_tools.js
The function `closeTunnel` was always returning `false`, since the `resolve` function was returning `undefined` and the function close of the running server that was mal formed, so it led to the tunnel not to close.
> Fix closeTunnel function

- README.md
- src/anonymize_proxy.js
- src/server.js
- src/tcp_tunnel_tools.js
- src/tools.js
- test/tools.js
Actually, looking at it, it might be best to just get rid of `parseUrl` completely and use `new URL()`, it only adds `scheme` to the parsed object which can be easily replaced by `protocol` around the code base
> Improving parseUrl() to handle IPv6 and other special URLs

- src/tools.js
- test/tools.js
Fixes BC break (parseUrl not returning scheme any more) in latest release.
> Add scheme to parseUrl output

- README.md
- src/anonymize_proxy.js
- src/handler_tunnel_chain.js
- src/index.js
- src/server.js
- test/anonymize_proxy.js
This is considered useful when some proxy providers may include useful information (e.g. for debugging) in the CONNECT response headers.
Implements #30.
This PR is based on the earlier commit in #31 (thanks @Benraay!) with these additional changes:
- Resolved conflicts between the earlier commit and the current `master` branch.
- Added a new test case for this very feature
- Slightly adjusted the callback interface in `listenConnectAnonymizedProxy`
- Renamed the event name (`onTrgRequestConnect` -> `tunnelConnectResponded`) for this may be accessed by users directly (via `server.on`).
> Exposing the CONNECT response details of chained tunnels via a new event

- src/tools.js
- test/tools.js
The checks is `isInvalidHeader` method are now backported from node's source.
Both methods were just a regexp checks, so it was trivial to use the very same
logic as in node.
The implementation changed a bit, `checkInvalidHeaderChar` is now implemented via regexp check,
and the `validateHeader` method was split into `validateHeaderName` and `validateHeaderValue`.
Both regexps are taken from the latest code from master. Also verified the exiting test in node,
but they seem to be aligned with the existing test suite (added only one additional assertion
for `undefined`).
Closes #50
> fix: remove dependency on node's `_http_common` module

- CHANGELOG.md
- README.md
- package.json
- src/tools.js
- test/anonymize_proxy.js
- test/tcp_tunnel.js
- test/tools.js
Proxy url returns standard ports for few protocols (see https://nodejs.org/api/url.html#url_url_port) when no port is explicitly specified.
Removed tests which needlesly require the standard port
- in `createTunnel`, only the parsed url is used in the end, so it should be ok
- in `anonymizeProxy`, the raw (unparsed) url is passed to `Server` through `prepareRequestFunction`. There it also uses only the parsed version.
Resolves #123
> parseUrl: return standard ports for http(s) when port is not specified

- README.md
- src/chain.ts
Would be useful to also pass the proxyChainId, for logging/tracking purposes on each connection.
> Pass proxyChainId to tunnelConnectResponded

- src/chain.ts
The following properties have probably been set by mistake and arent needed there.
> chore: remove unused properties

- src/chain.ts
- src/direct.ts
- src/forward.ts
- src/server.ts
family option is needed in order to use ipv6 as localAddress or upstream, since otherwise dns.lookup only returns one ipv4 address. #219
> feat: family option

- README.md
- package.json
- src/custom_connect.ts
- src/server.ts
- test/server.js
This would enable to use CONNECT for SERP requests. Currently using [`hpagent`](https://github.com/delvedor/hpagent) doesn't work when doing SERPs, because it only supports CONNECT proxying.
/cc @AndreyBykov
> feat: custom connect http server

- README.md
The previous example doesn't set the port and the code fallback to the DEFAULT_PROXY_SERVER_PORT no random port in this configuration.
Another patch is possible `port: 0` but is less explicit.
```
const newProxyUrl = await proxyChain.anonymizeProxy({ url: oldProxyUrl, port: 0 });
```
> docs: Fix example for anonymizeProxy

- src/server.ts
https://nodejs.org/api/net.html#event-timeout `Emitted if the socket times out from inactivity. This is only to notify that the socket has been idle. The user must manually close the connection.`
> fix: Handle socket timeout to prevent connections from leaking

- src/custom_connect.ts
See the discussion here: https://github.com/apify/proxy-chain/issues/521#issuecomment-1685378805
NOTE: I tried running `npm run test` to ensure everything works. But the tests were failing because of other error (below) even before I made the change, so I can't ensure integrity.
```sh
$ npm run test
> proxy-chain@2.3.0 test
> nyc cross-env NODE_OPTIONS=--insecure-http-parser mocha --bail
(node:23123) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
1) supports localAddress
0 passing (2s)
1 failing
1) supports localAddress:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/presenter/repos/proxy-chain/test/server.js)
at listOnTimeout …
```
> refactor: Avoid accessing prototype in custom_connect

- README.md
- package.json
- src/anonymize_proxy.ts
- src/server.ts
I've added support for specifying `host` used for the `listen` call. This will enable users to e.g. listen on `localhost`, which can be more secure than the default unspecified IP address (0.0.0.0).
> feat: Add option to specify server's `host`

- README.md
- package.json
- src/chain.ts
- src/chain_socks.ts
- src/direct.ts
- src/forward_socks.ts
- src/server.ts
- src/statuses.ts
This PR introduces support for SOCKS protocol.
> feat: support SOCKS proxy

- package.json
- src/anonymize_proxy.ts
- src/server.ts
- test/anonymize_proxy.js
- test/socks.js
This PR fixes validation of URL protocol for `anonymize_proxy.ts`
> fix: correctly validate protocols in anonymize_proxy

- package.json
- src/chain_socks.ts
- test/socks.js
This PR decodes URI component for username and password for SOCKS tunnel. This is already done inside the library used for forward SOCKS, so I'm adding it to chain SOCKS as well.
Closes #548
> fix: decode username and password for socks tunnel

- test/README.md
- test/server.js
So that the tests may pass in my local environment (tried Node.js 20 (active LTS) and 18).
The CI tests however seem to be [configured to run only with Node.js 14 and 16](https://github.com/apify/proxy-chain/blob/b326f95855680cae28e80518a16662124e12c438/.github/workflows/check.yaml#L18).
> chore: minor test enhancements

- src/chain.ts
> close targetSocket when proxy replies with non-200 status

- src/chain.ts
- src/server.ts
- test/server.js
> https support for proxy relay

- src/server.ts
The connection ID log prefix for the first request is missing because `connectionId` starts from 0.
> fixed missing log prefix for the first request

- .github/scripts/before-beta-release.js
- .github/workflows/check.yaml
- .github/workflows/release.yaml
- eslint.config.mjs
- jest.config.ts
- package.json
- src/chain.ts
- src/forward.ts
- src/utils/count_target_bytes.ts
This PR attempts to fix incorrect stats due to the reuse of target sockets for HTTP(S) protocols. 
Based on https://github.com/apify/proxy-chain/pull/572
Note: I was forced to upgrade `actions/cache` as `v2` was deprecated and it wouldn't run with it.
I also had to edit eslint config to run with `.` instead of `src` and excluded `tests`, because with `src` the CI was failing (no idea why). 
The files changed in `src` are the ones relevant for the main topic of this PR.
> fix: correct target stats when sockets are reused

- .github/scripts/before-beta-release.js
- eslint.config.mjs
- package.json
- src/anonymize_proxy.ts
- src/chain.ts
- src/chain_socks.ts
- src/custom_connect.ts
- src/custom_response.ts
- src/direct.ts
- src/forward.ts
- src/forward_socks.ts
- src/server.ts
- src/socket.ts
- src/statuses.ts
- src/tcp_tunnel_tools.ts
- src/utils/count_target_bytes.ts
- src/utils/get_basic.ts
- src/utils/normalize_url_port.ts
- src/utils/parse_authorization_header.ts
- src/utils/redact_url.ts
- src/utils/valid_headers_only.ts
This PR updates the `@apify/eslint-config` to a stable version
> chore: update shared eslint config to a stable version

- README.md
- src/anonymize_proxy.ts
- src/chain.ts
- src/forward.ts
- src/server.ts
- src/tcp_tunnel_tools.ts
As title. E.g.:
```
const server = new Server({
prepareRequestFunction: () => ({
upstreamProxyUrl: 'https://user:pass@myproxy:8080',
ignoreUpstreamProxyCertificate: true  // Useful for self-signed cert
})
}).listen();
```
Anonymize:
```
anonymizeProxy({
url: 'https://user:pass@myproxy:8080',
ignoreProxyCertificate: true,
}).then((anonymizedURL) => {
console.log(`Anonymized URL: ${anonymizedURL}`);
});
```
Create tunnel:
```
createTunnel(
'https://user:pass@myproxy:8080',
targetHost,
{ ignoreProxyCertificate: true }
).then((url) => {
console.log('Tunnel endpoint:', url);
});
```
> Add HTTPS upstream proxy support with option to ignore proxy cert errors

- package.json
- test/server.js
Add tests for `ignoreUpstreamProxyCertificate` proxy chain server `prepareRequestFunction` option.
> test: add ignoreUpstreamProxyCertificate tests
